new_year_resolutions = [
    "Exercise regularly",
    "Lose weight",
    "Eat healthier",
    "Save more money",
    "Spend less time on social media",
    "Learn a new skill or hobby",
    "Read more books",
    "Quit smoking",
    "Drink less alcohol",
    "Get organized",
    "Travel to new places",
    "Spend more time with family and friends",
    "Reduce stress",
    "Get more sleep",
    "Start a gratitude journal",
    "Volunteer or give back to the community",
    "Improve time management",
    "Pay off debt",
    "Advance in your career",
    "Take better care of your mental health",
    "Practice mindfulness or meditation",
    "Declutter and simplify your life",
    "Cook more meals at home",
    "Drink more water",
    "Learn a new language",
    "Be more eco-friendly",
    "Start a side hustle",
    "Stop procrastinating",
    "Set boundaries and say no more often",
    "Focus on self-care"
]
